---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "pavit-onlineveg"
  namespace: "default"
  labels:
    app: "pavit-onlineveg"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "pavit-onlineveg"
  template:
    metadata:
      labels:
        app: "pavit-onlineveg"
    spec:
      containers:
      - name: "onlinevegetablesale-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/pavithracherukuri/onlinevegetablesale@sha256:5231761f0a2ed9549d82c1b4fb1186ce3fb33ceb59b2aa2496e2b9ad2f515ed6"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pavit-onlineveg-hpa-9bl4"
  namespace: "default"
  labels:
    app: "pavit-onlineveg"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pavit-onlineveg"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
