
  ---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "team-4"
  namespace: "default"
  labels:
    app: "team-4"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "team-4"
  template:
    metadata:
      labels:
        app: "team-4"
    spec:
      containers:
      - name: "onlinevegetablesale-sha256-1"
        image: "gcr.io/cap1-339903/github.com/pavithracherukuri/onlinevegetablesale@sha256:b3f4110a0fa21278cd0cd341df815c0a2a2b577dc863f63b0381b067ec3635c5"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "team-4-hpa-tvjs"
  namespace: "default"
  labels:
    app: "team-4"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "team-4"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

