---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "pavithra"
  namespace: "default"
  labels:
    app: "pavithra"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "pavithra"
  template:
    metadata:
      labels:
        app: "pavithra"
    spec:
      containers:
      - name: "onlinevegetablesale-sha256-1"
        image: "gcr.io/cap1-339903/github.com/pavithracherukuri/onlinevegetablesale@sha256:20fdb57b9675fd30743a2ea1bb1c76df366f34c0083cb1ad0ee13f6987ed2ad3"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pavithra-hpa-exzi"
  namespace: "default"
  labels:
    app: "pavithra"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pavithra"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
